### ISSUE TITLE
ERROR Error: Uncaught (in promise): Failed login session

### ISSUE THREAD

**Issue by ajoykarmakar** [ionicthemes/ionic2-twitter-login#2]
Hi, you create a awesome stuff but I got an error while logging
 `Error: Uncaught (in promise): Failed login session
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:4394)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
defaultErrorLogger @ main.js`

Only getting the loading screen, can you please help me?

![screenshot_1516124160](https://user-images.githubusercontent.com/32778214/35003139-e260dc94-fb11-11e7-9cd6-0c151d3a13f5.png)

**Comment by djabif** [comment]
Please debug your app on the login method to have more information.

**Comment by ajoykarmakar** [comment]
The login is working very good on android lollipop version but in marshmallow and in the emulator (emulator has nougat version) it doesn't work..can you please assist me to step by step to fix this issue?

**Comment by djabif** [comment]
We have now updated the repo to ionic v4. Everything should work now!
